---
title: "RF attempt 1, all vars"
author: "Sebastian"
date: "April 22, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(randomForest)
library(caret)

set.seed(202)
df = read.csv('../data/OnlineNewsPopularity.csv')

# ignoring url, timedelta, and LDA vars
df[,c('url', 'timedelta', 'LDA_00', 'LDA_01', 'LDA_02', 'LDA_03', 'LDA_04')] = list(NULL)

train = createDataPartition(df$shares, p=0.66, list=F)
X = df[,-(ncol(df))]
y = df$shares

Xtrain = X[train,]
Xtest = X[-train,]
ytrain = y[train]
ytest = y[-train]
```

Load the data, X/y, train-test split.

```{r}
trControl = trainControl(method='cv', number=3)
modelLookup(model='rf')
# only one hyperparameter in this implementation of rf???
tuneGrid = expand.grid(mtry=c(sqrt(ncol(X)), ncol(X)/4, ncol(X)/3, ncol(X)/2, ncol(X)))
```

Set how the cross-validation should be done and look up the available hyperparams for `rf`. We're using 10-fold CV repeated 5 times and there's only one hyperparameter, `mtry`, available for `rf`.

```{r}
model.rf = train(Xtrain, ytrain, method='rf', 
                 trControl=trControl, tuneGrid=tuneGrid,
                 metric='Rsquared', maximize=T)
plot(model.rf)
```

```{r}
varImp(object=model.rf)
```







